- name: Setup mgmt
  hosts: all
  gather_facts: no
  become: yes
  become_user: root
  
- import_playbook: /home/rocky/threat-hunting-lab-ELK/ansible/playbooks/install_k3s.yml

- import_playbook: /home/rocky/threat-hunting-lab-ELK/ansible/playbooks/
# - import_playbook: /home/rocky/threat-hunting-lab-ELK/ansible/playbooks/pvcpath.yml
