- name: Deploy ELK Stack via Helm
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Ensure Elastic Helm repo is added for root
      ansible.builtin.command:
        cmd: /usr/local/bin/helm repo add elastic https://helm.elastic.co
        creates: /root/.config/helm/repositories.yaml

# elasticsearch
    - name: Install Elasticsearch
      kubernetes.core.helm:
        name: elasticsearch
        chart_ref: elastic/elasticsearch
        release_namespace: default
        values_files:
          - "../../ELK-roles/elasticsearch/values.yml"
        wait: true
        wait_timeout: 10m0s
        binary_path: /usr/local/bin/helm
        kubeconfig: "{{ lookup('env', 'HOME') }}/.k3s/k3s.yaml"
      environment:
        PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}"
        # # 強制指向一個固定的目錄，確保不論切換到什麼使用者，都能讀取到同一個 repo 設定
        # HELM_REPOSITORY_CONFIG: "/tmp/helm-repositories.yaml"

# kibana
    - name: Install Kibana
      kubernetes.core.helm:
        name: kibana
        chart_ref: elastic/kibana
        release_namespace: default
        values_files:
          - "../../ELK-roles/kibana/values.yml"
        wait: true
        wait_timeout: 10m0s
        binary_path: /usr/local/bin/helm
        kubeconfig: "{{ lookup('env', 'HOME') }}/.k3s/k3s.yaml"
      environment:
        PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}"
        # # 強制指向一個固定的目錄，確保不論切換到什麼使用者，都能讀取到同一個 repo 設定
        # HELM_REPOSITORY_CONFIG: "/tmp/helm-repositories.yaml"
