name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build OPENCVE Docker image
        working-directory: CVE-Vulnerability/OPENCVE-Docker/opencve-docker
        env:
          OPENCVE_REPOSITORY: https://github.com/opencve/opencve.git
          OPENCVE_VERSION: 1.4.1
        run: |
          docker build . --file Dockerfile --tag opencve-docker:latest \
            --build-arg OPENCVE_REPOSITORY=${OPENCVE_REPOSITORY} \
            --build-arg OPENCVE_VERSION=${OPENCVE_VERSION}
